### ISSUE TITLE
locales not affecting output?

### ISSUE THREAD

**Issue by jameswragg** [KSDaemon/nunjucks-intl#25]
When setting `locales: "de-DE"` in my `intl` object the output of `formatNumber(NUM)` is unaffected, which seems pretty fundamental so assuming I'm doing something wrong but I can't see what?

This is also the same for `formatDate` etc.

I've put together a testcase here:
https://codesandbox.io/s/immutable-thunder-41wpv

**Comment by KSDaemon** [comment]
Hi! 
Hmm... Don't use it for a long time :) 
I think this can be related to node can be built with only English locale by default.
Have a look here: https://nodejs.org/api/intl.html#intl_detecting_internationalization_support

**Comment by jameswragg** [comment]
Ok that's cool. I guess hoped the npm dependency bumps were signs it was actively maintained.
I think I'll look into integrating [i18next](https://www.i18next.com/) with Nunjucks instead.

**Comment by KSDaemon** [comment]
Well, Actually i do not want to discontinue this lib. Right now i just have no time, but i'm planning to use it a little bit later.
All underlying deps packages, that were at rest for a long time now are actively updating (even more often then normal packages should do), and event all Yahoo staff is no merged into monorepo of FormatJs. When i have time, i tried to update dependencies to be up to date, and even in current node tests are passed. There are some troubles with old node envs.
Will be great, if you can help with that! ;) I don't think it will take too much time, but we can have already working project to be up to date! 
What do you think @jameswragg ? :)
