### ISSUE TITLE
Syntax Error:  Cannot use import statement outside a module

### ISSUE THREAD

**Issue by vtrphan** [KSDaemon/nunjucks-intl#47]
Hello, i'm getting this error trying to use it  in my nestjs/typescript application

```
...\node_modules\nunjucks-intl\src\nunjucks-intl.js:1
import IntlMessageFormat from 'intl-messageformat';
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:999:16)
```

Please advise

**Comment by GerritKuilder** [comment]
Yep, met too.... same error.

**Comment by Dianoga** [comment]
It looks like the `package.json` file is point `main` at `index.js`. But that file is explicitly include the file from `src` instead of the generated one is `dist`.

**Comment by vtrphan** [comment]
@Dianoga is correct, pls fix it

**Comment by Dianoga** [comment]
For now I've downgraded to 1.0.0 which is working.

Otherwise if your workflow involves a transpiler (babel or typescript), it's possible to make those also work on this module. It's not ideal though.

**Comment by 49-22** [comment]
Facing same issue.
The generated `index.js` file in the node_modules, is pointing to `src` folder rather than `dist` which is causing this behaviour.
Manually changing from `src` to `dist` in the index.js file is fixing the issue.
